Asset Delivery & Resizing Separated.
monstercat/asset-delivery pull request #8
Opened 2021-12-03 19:21 UTC by bryancua

Asset delivery was slow on first load of every image as it required waiting for the process to finish resizing before pointing the user to a URL from which the asset can be downloaded. This was fixed by returning the original URL if a resized version could not be found and performing resizing in a goroutine. 

However, goroutines are automatically killed at the end of any request by Google Cloud Run (which is what we use to run the delivery). Therefore, this did not work. 

This PR moves the resizing functionality to a public function which is managed by Google Cloud Functions. It is meant to be connected to a specific PubSub topic. The original delivery server now sends a message on that PubSub topic to start the process. 

TODO: Externalize the topic in an environment variable 

TODO: find a way to stop duplicate images from being created (perhaps we can use Redis/MemCached to create a key using the hash, the width, and the encoding format. This key could be deleted once encoding is finished, and the value of the key could be an expiry after which the function should attempt to recreate the file).

2021-12-03 20:01 UTC, DerrickGold commented on cmd/resize/main.go
> +	// TODO: by flag, decide to use an HTTP server, or a subscription directly on pubsub.
Is this expected to be run on Cloud Functions? If so you'll have to have the cloud function directly subscribed to pub sub since cloud functions have a max run time of 540 seconds.

2021-12-03 20:18 UTC, DerrickGold commented on cmd/delivery/server.go
> +		log.Printf("Could not send resize command. %s", err)
This seems like a pretty serious error that could easily be missed. Are there plans to use google logging to make sure this is visible? Last thing you want is your asset resizer to silently not be working for a week because the credentials are configured incorrectly or were rotated to a different set, or the pub sub topic was changed, etc.

2021-12-03 20:35 UTC, bryancua commented on cmd/resize/main.go
> +	// TODO: by flag, decide to use an HTTP server, or a subscription directly on pubsub.
I'm gonna do it on Cloud Run. Cloud Functions doesn't allow from Github. Only Cloud Source Repositories. 
https://cloud.google.com/run/docs/tutorials/pubsub

Basically setup a PUSH endpoint for the pubsub message

2021-12-03 20:35 UTC, bryancua commented on cmd/delivery/server.go
> +		log.Printf("Could not send resize command. %s", err)
Yes. I will be adding google logging before changing this to ready for review =)

2021-12-03 20:36 UTC, bryancua commented on cmd/resize/main.go
> +	// TODO: by flag, decide to use an HTTP server, or a subscription directly on pubsub.
![image](https://user-images.githubusercontent.com/48697038/144669533-d5b7bc40-1ea8-461e-9b04-7a6de37347e4.png)

2021-12-03 20:36 UTC, bryancua commented on cmd/resize/main.go
> +	// TODO: by flag, decide to use an HTTP server, or a subscription directly on pubsub.
This is in PubSub / Subscriptions / Edit

2021-12-03 20:40 UTC, DerrickGold commented on cmd/resize/main.go
> +	// TODO: by flag, decide to use an HTTP server, or a subscription directly on pubsub.
It should be possible to deploy cloud functions from github:
https://cloud.google.com/functions/docs/deploying/repo 

But I guess it really just mirrors github on their internal repository. There's probably a way to hook into code build to deploy a cloud function from our repo.

2021-12-03 20:53 UTC, bryancua commented on cmd/resize/main.go
> +	// TODO: by flag, decide to use an HTTP server, or a subscription directly on pubsub.
Yea I think I preferred to control it with Cloud Build? We could also serve from ZIP in storage but again... everything in cloud build is just nicer

2021-12-03 20:55 UTC, bryancua commented on cmd/resize/main.go
> +	// TODO: by flag, decide to use an HTTP server, or a subscription directly on pubsub.
Like this just annoyed me real fast. 

(Screenshot from Cloud Functions / Create Function; Go 1.13 is an option, but go1.16 is still in preview)
![image](https://user-images.githubusercontent.com/48697038/144671560-a5d8688b-4d42-48a9-811f-90fc2f7c2272.png)

2021-12-03 21:03 UTC, bryancua commented
@DerrickGold Logging added =)

2021-12-06 17:33 UTC, tmathews requested changes

2021-12-06 17:33 UTC, tmathews commented on cmd/resize/main.go
> +	// TODO: by flag, decide to use an HTTP server, or a subscription directly on pubsub.
@bryancua you can setup repository mirroring for a Cloud Source repo. No need to do it in Cloud Run.

2021-12-06 17:33 UTC, tmathews commented on cmd/resize/main.go
> +	opts := option.WithCredentialsFile(filename)
Replace filename param with opts param, rather than calling option.WithCredentialsFile every time.

2021-12-06 17:33 UTC, tmathews commented on cmd/resize/main.go
> +	opts := option.WithCredentialsFile(filename)
Move to lib.

2021-12-06 17:33 UTC, tmathews commented on resize.go
> +func Resize(fs *GCloudFileSystem, opts ResizeOptions) error {
Should swap fs *GCloudFileSystem to FileSystem

2021-12-06 17:43 UTC, bryancua commented on cmd/resize/main.go
> +	// TODO: by flag, decide to use an HTTP server, or a subscription directly on pubsub.
But it also means that anything pushed is automatically deployed, I think. Do we want that? 
I also am unsure about how to pass in parameters through Cloud Functions.

2021-12-06 17:43 UTC, bryancua commented on cmd/resize/main.go
> +	opts := option.WithCredentialsFile(filename)
Ok.

2021-12-06 17:43 UTC, bryancua commented on resize.go
> +func Resize(fs *GCloudFileSystem, opts ResizeOptions) error {
ok.

2021-12-06 17:46 UTC, DerrickGold commented on cmd/resize/main.go
> +	// TODO: by flag, decide to use an HTTP server, or a subscription directly on pubsub.
Configure it to auto deploy to a non-prod environment first. Then it should be easy enough to manually deploy the prod version after tests have passed.

As for passing arguments, since you're not directly invoking the cloud function, they'd have to be set as environment variables. Any run time parameters that need to be provided should be included in the pub/sub message.

Since both a test and prod environment might be operating on the same messages, maybe it's worth having a field in the message to indicate what domain the message originates from (e.g. Domain: "test" indicating only the test environment will process the pubsub and not prod)

2021-12-06 18:10 UTC, bryancua commented on cmd/resize/main.go
> +	// TODO: by flag, decide to use an HTTP server, or a subscription directly on pubsub.
Created a new PR for moving resize command into Cloud Functions https://github.com/monstercat/asset-delivery/pull/9

My understanding is delivery is staying where it is? Or should I change that to a cloud function as well
@tmathews @DerrickGold 

If so, I'd like to do it after i can confirm that cloud functions is working for the resize part.

2021-12-06 18:22 UTC, DerrickGold commented on cmd/delivery/server.go
> +	if err := s.PB.Publish(ResizeTopic, b); err != nil {
At this point, we might not even need pub/sub to call the cloud function. You can use the sdk to call the function directly: https://cloud.google.com/go/docs/reference/cloud.google.com/go/functions/latest/apiv1

Pub/Sub is a good mechanism for hooking multiple other processes on a global system events. But given the scope of this event, it's a bit overkill and will cost us more.

2021-12-06 18:26 UTC, bryancua commented on cmd/delivery/server.go
> +	if err := s.PB.Publish(ResizeTopic, b); err != nil {
I'll add a separate PR for this. Thanks

2021-12-06 19:49 UTC, bryancua commented on cmd/delivery/server.go
> +	if err := s.PB.Publish(ResizeTopic, b); err != nil {
![image](https://user-images.githubusercontent.com/48697038/144912503-4f8f1e40-f814-44af-a065-a372d8d13434.png)

2021-12-06 19:51 UTC, bryancua commented on cmd/delivery/server.go
> +	if err := s.PB.Publish(ResizeTopic, b); err != nil {
i can't find a command to async call functions. do u know of one i am missing? @DerrickGold

2021-12-06 19:55 UTC, DerrickGold commented on cmd/delivery/server.go
> +	if err := s.PB.Publish(ResizeTopic, b); err != nil {
Ah well that's annoying. I guess there isn't an async option to call it other than triggering it through another service. 😞 Great way to make more money.

2021-12-06 21:16 UTC, bryancua commented on cmd/delivery/server.go
> +	if err := s.PB.Publish(ResizeTopic, b); err != nil {
Indeed. I would have loved an `InvokeFunction` method which just sends the command. 

But i seems they have some cool ways to trigger cloud functions, though a lot of it centers around PubSub. https://cloud.google.com/functions/docs/calling
- https://cloud.google.com/functions/docs/calling/storage
- https://cloud.google.com/functions/docs/calling#cloud_logging
- https://cloud.google.com/functions/docs/calling#gmail

2021-12-06 21:28 UTC, bryancua commented on cmd/resize/main.go
> +	// TODO: by flag, decide to use an HTTP server, or a subscription directly on pubsub.
https://github.com/GoogleCloudPlatform/golang-samples/issues/1600
fml lol

2021-12-07 00:01 UTC, DerrickGold commented on README.md
> +- **allowedHosts**: A comma separated list of domain hosts. An empty value allows any.
Might want to further expand on this for clarity. What are these hosts allowed for?

2021-12-07 00:03 UTC, DerrickGold commented on cmd/delivery/server.go
> +	if r.Method != "GET" {
Not necessary, but it might be nice to have the logger created up here so that you can log the non-GET method and resize options error traffic.

2021-12-07 00:06 UTC, DerrickGold commented on cmd/delivery/server.go
> +	l := &logger.Contextual{
You could pass in the logger so that the same logging context is used for all requests. 

Also, I'm not sure if the environment already includes a request ID, but it would be useful to generate one for the log context so that all logs for a single invocation can be easily searched.

2021-12-07 00:14 UTC, DerrickGold commented on gcp-cloud-function.go
> +func GcfResize(ctx context.Context, m PubSubMessage) error {
Seems weird that we need to define a struct that only contains `Data`. Like the field would always be the same at that point and they might as well just pass in a `[]byte` field directly. 

Is there some automatic unmarshalling to the target struct `ResizeOptions` that could be used here?

2021-12-07 00:14 UTC, bryancua commented on cmd/delivery/server.go
> +	if r.Method != "GET" {
ah yes

2021-12-07 00:16 UTC, bryancua commented on cmd/delivery/server.go
> +	l := &logger.Contextual{
I'll add a TODO to add a request id.

2021-12-07 00:16 UTC, DerrickGold commented on gcp-cloud-function.go
> +	log.Printf("Hash: %s", data.HashSum)
Use `cloudLogger` here?

2021-12-07 00:17 UTC, bryancua commented on gcp-cloud-function.go
> +func GcfResize(ctx context.Context, m PubSubMessage) error {
This is based on their example code ^o) I didn't really want to mess with it. 
https://cloud.google.com/functions/docs/calling/pubsub#functions-calling-direct-pubsub-http-go

2021-12-07 00:17 UTC, bryancua commented on gcp-cloud-function.go
> +	log.Printf("Hash: %s", data.HashSum)
CloudLogger already gets the hash through the context. This is for the non-cloud-logger side of things

2021-12-07 00:19 UTC, bryancua commented on gcp-cloud-function.go
> +func GcfResize(ctx context.Context, m PubSubMessage) error {
And i didn't really want to inline a struct in a function parameter XD

2021-12-07 00:21 UTC, DerrickGold commented on messager-gcloud.go
> +	_, err := res.Get(context.Background())
Might be nice to log the ID of the message generated by this request for tracing purposes.

2021-12-07 00:24 UTC, DerrickGold commented on resize.go
> +	height = int(float64(target) * ratio)
Do we have any max dimensions that we want to support? There's a mix of 64 bit and 32 bit numbers here and there's an overflow waiting to happen.

2021-12-07 00:27 UTC, DerrickGold commented on resize.go
> +	height = int(float64(target) * ratio)
Also `uint64 -> float64 -> int` is all over the place and might have some unintended side effects.

2021-12-07 00:28 UTC, bryancua commented on resize.go
> +	height = int(float64(target) * ratio)
i think Y and X are both 32 bit ints so the only 64-bit thing here is a float.

2021-12-07 00:30 UTC, bryancua commented on resize.go
> +	height = int(float64(target) * ratio)
MaxImageDimension is 4096 and is set by the URL parameters when reading on the Delivery side. The GCF doesn't have any checks itself tho. I thought it would be okay seeing as it is called by either an admin or through the delivery route. Should it be capped too?

2021-12-07 00:31 UTC, bryancua commented on resize.go
> +	height = int(float64(target) * ratio)
Why is target a `uint64`

2021-12-07 00:32 UTC, DerrickGold commented on resize.go
> +	height = int(float64(target) * ratio)
Depending on the inputs `float64(target) * ratio` could still produce a value that only 64 bits can contain. In that case height would overflow and become a negative value and likely crash hard.

We should make sure the code is safe to use for all edge cases so that when we revisit this in the distance future and want to increase the image size, we don't end up with an unexplained crash. Or in the event that the code gets refactored, the function itself shouldn't crash when any original context is lost.

2021-12-07 00:33 UTC, bryancua commented on resize.go
> +	height = int(float64(target) * ratio)
https://github.com/monstercat/asset-delivery/blob/main/server.go#L216
lolz

2021-12-07 00:36 UTC, bryancua commented on resize.go
> +	height = int(float64(target) * ratio)
Changed

2021-12-07 00:40 UTC, bryancua commented on resize.go
> +	height = int(float64(target) * ratio)
> Depending on the inputs float64(target) * ratio could still produce a value that only 64 bits can contain. In that case height would overflow and become a negative value and likely crash hard.

Practically speaking this is impossible tho. Our server would crash before it could finish going through an image with a width > 32-bits can handle.

2021-12-07 00:54 UTC, DerrickGold approved these changes

2021-12-07 01:01 UTC, tmathews approved these changes

2021-12-07 01:03 UTC, merged